image: node:23.11.0

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
    variables:
        # Enable only in dire need!
        # VITEPRESS_IGNORE_DEAD_LINKS: "1"
    script:
        - npm install
        - npm run docs:build
        - mv docs/.vitepress/dist public
    artifacts:
        paths:
            - public
    only:
        - master
        - feat.cicd
